### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by jarodium** [Oberto/php-image-magician#8]
Hello Jarrod
I would like to know what type of licensing the software is using.
I have tried http://phpimagemagician.jarrodoberto.com/license.html but it has 404.

Cheers

**Comment by Oberto** [comment]
Hi Jarodium,

Use as you see fit (except for selling the code). You can use this library for either personal or commercial code. Attribution is encouraged, but not required.   :) 

Thanks for pointing that out the dead link, I'll get that fixed.
